name: Deploy on GitHub Pages

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
<<<<<<< HEAD
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
=======
        key: ${{ runner.os }}-node-${{ hashFiles('*/blog/package-lock.json') }}
>>>>>>> 0c4d3b3de955eab487e19a0f05275c7b47bf86d1
        restore-keys: |
          ${{ runner.os }}-node-

    - name: install
      run: npm install --frozen-lockfile

    - name: build
      run: npm run build

    - name: export
      run: npm run export

    - name: add nojekyll
      run: touch ./out/.nojekyll

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
<<<<<<< HEAD
        publish_dir: ./out
=======
        publish_dir: ./out
>>>>>>> 0c4d3b3de955eab487e19a0f05275c7b47bf86d1
